### ISSUE TITLE
Got some errors on PHP 5.5

### ISSUE THREAD

**Issue by rayzru** [stefangabos/Zebra_Database#23]
This one faults with an error `cannot use [] for reading`

`... && $this->cached_results[] = ...`

Should be replaced with array_push, i guess.

**Comment by stefangabos** [comment]
Should be fixed now.
Thanks!

**Comment by rayzru** [comment]
@stefangabos, sorry mate, there is same construction missed a littile bit below.
Look at 2330 now.

```PHP
if (isset($_SESSION[$key]) && isset($_SESSION[$key . '_timestamp']) && $_SESSION[$key . '_timestamp'] + $cache > time() && $this->cached_results[] = @unserialize(gzuncompress(base64_decode($_SESSION[$key])))) {
```

**Comment by stefangabos** [comment]
Should be fixed now. Thanks again!
