### ISSUE TITLE
Notice 

### ISSUE THREAD

**Issue by rayzru** [stefangabos/Zebra_Database#24]
Hello there again! There is a notice when am making static call using this class with a singleton instance getter. 
```
Undefined property: database::$total_execution_time in Zebra_Database.php on line 2402
```
So, adding `$total_execution_time` into private vars fixes it.

**Comment by stefangabos** [comment]
Fixed. Thanks!

**Comment by stefangabos** [comment]
Even though the fix was needed, you may want to use your singleton like here https://github.com/stefangabos/Zebra_Database/issues/12#issuecomment-52415286

**Comment by rayzru** [comment]
It defenetly looks similar to this. So yeah. Sure :)
