### ISSUE TITLE
Fatal error - using fetch_obj_all

### ISSUE THREAD

**Issue by Johnyz** [stefangabos/Zebra_Database#26]
When using fetch_obj_all("id") with column name, I got error:

Fatal error: Cannot use object of type stdClass as array in ....  Zebra_Database.php on line 1438

Simplified example:
$db->select('*', 'user');
$result = $db->fetch_obj_all("id");

**Comment by stefangabos** [comment]
Fixed. Thanks a lot for reporting!

**Comment by Johnyz** [comment]
:+1:
