### ISSUE TITLE
how to use LIKE %...%

### ISSUE THREAD

**Issue by mrqaidi** [stefangabos/Zebra_Database#29]
hello

thanks for this awesome class   . i am stuck with  something that not working like 

LIKE %...%

example  query : $sql = "SELECT \* FROM `postcodes_seo` WHERE `Postal_Sector` LIKE \'%E1%\'";

**Comment by primeinc** [comment]
When in doubt use the query function. http://stefangabos.ro/wp-content/docs/Zebra_Database/Zebra_Database/Zebra_Database.html#methodquery

'''php
$db->query('
    SELECT
        *
    FROM
        postcodes_seo
    WHERE
        Postal_Sector LIKE \'%E1%\'
');
'''

**Comment by etb09** [comment]
You might also use select.
`$db->select('*'. 'postcodes_seo', 'Postal_Sector LIKE ?', array("%E1%"));`

It is also suggested to use the escape functionality in query or select, if possible.  Maybe not if you have a fixed value but in all other cases.

```
$db->query('
    SELECT
        *
    FROM
        postcodes_seo
    WHERE
        Postal_Sector LIKE \'%?%\'
', array('E1'));
```

**Comment by stefangabos** [comment]
Alternatively, you can also use it like

```php
$db->query('
    SELECT
        *
    FROM
        postcodes_seo
    WHERE
        Postal_Sector LIKE "%' . $db->escape($value) . '%"
');
```
