### ISSUE TITLE
Help with translations

### ISSUE THREAD

**Issue by stefangabos** [stefangabos/Zebra_Database#31]
@rayzru, @ebroda can you please help with translating the 2 new entries in the Russian and German language files? The new entries are "invalid_option" and "options_before_connect". Thank you!

**Comment by rayzru** [comment]
I can't find those keys usages or english interpretation. 
`invalid_option` is pretty predictable but `options_before_connect` is not.
Can you please provide more info?

**Comment by stefangabos** [comment]
In the end, there are quite a few things to translate. These are those entries

`explain`
`invalid_option`
`options_before_connect`
`seconds`
`unbuffered`
`unbuffered_queries_cannot_be_cached`
`unusable_method_unbuffered_queries`

Thanks!
