### ISSUE TITLE
* joker not working

### ISSUE THREAD

**Issue by boileau** [stefangabos/Zebra_Database#32]
Hi Stefan,

SELECT 
    `*` 
FROM 
    `Table`
give error:
Unknown column '*' in 'field list'
on ZD 2.9.6

**Comment by stefangabos** [comment]
This is fixed in dbb156a but not yet made available as a release. I will do a release now and you'll have it. Thanks!

**Comment by stefangabos** [comment]
Done. [2.9.7](https://github.com/stefangabos/Zebra_Database/releases/tag/2.9.7) is now available.

**Comment by boileau** [comment]
Thanks !
