### ISSUE TITLE
Can't use alias with SELECT

### ISSUE THREAD

**Issue by jasonl1** [stefangabos/Zebra_Database#34]
I used to be able to use alias' with SELECT() on 2.8.3, but on the latest version I get an SQL error. For example:
1. $db->select('o_fname AS firstName','active','','','','10');
2. $db->query('SELECT o_fname AS firstName FROM active LIMIT 10');

Both used to work in 2.8.3 but now 1 fails because SELECT escapes the column (including the alias). Do I have to rewrite my queries or could this be addressed in the future?
<img width="576" alt="screen shot 2017-07-19 at 3 38 33 pm" src="https://user-images.githubusercontent.com/7989408/28386064-6a9ec66a-6c98-11e7-8515-93693ff8081d.png">

**Comment by stefangabos** [comment]
Since in a `SELECT` statement there can be pretty complex stuff, I prefer to leave it like that, instead of writing code to detect what it should escape and what not. The `select` method was intended for *very* simple statements (although, I do realise that using `AS` still counts as being simple) and never thought that people would start and abuse it :) I had lots of requests regarding the method and is the one method from this library that I never, ever used it myself. So, yes, I would recommend rewriting your queries (if that is possible). Other than that, I could maybe add a method/property to disable escaping for the `select` method.

**Comment by jasonl1** [comment]
Thanks Stefan. What i ended up doing was adding a check for the 'AS' alias in the function _escape
`  private function _escape($entries) {

        // treat argument as an array
        $entries = (array)$entries;

        $result = array();

        // iterate over the entries given as argument
        foreach ($entries as $entry) {

            // explode string by dots
            $entry = explode('.', $entry);

            // iterate over the segments
            $entry = array_map(function($value) {

                // trim ticks and whitespace
                $value = trim(trim($value, '`'));

                // if not * or a MySQL function
                if ($value !== '*' && !$this->_is_mysql_function($value))
                    // escape for alias
                    if(stripos($value, " as " )){
                        $v = explode(" as ",str_replace(" AS ", " as ",$value));
                        // enclose value in grave accents
                        return '`' . $v[0] . '` AS ' . $v[1];
                    }
                    // enclose value in grave accents
                    return '`' . $value . '`';

                // return the value as it is otherwise
                return $value;

            }, $entry);

            // concatenate the string back and add it to the result
            $result[] = implode('.', $entry);

        }

        // recompose the string and return it
        return implode(', ', $result);

    }`

**Comment by stefangabos** [comment]
Ok, I've implemented your suggestion 😄 
Thanks!

**Comment by jasonl1** [comment]
thanks Stefan, looks like it may need a bit more work, if there is an SQL function with the alias

**Comment by stefangabos** [comment]
if there's an SQL function anywhere, everything is returned as it is because of the call to `_is_mysql_function` at line 4492

**Comment by jasonl1** [comment]
i can see why the select is just for simple queries - many cases to consider, like nested functions. Great job on the plugin still!

**Comment by stefangabos** [comment]
Well, it works with nested functions also...if it finds at least one
function, any function, it doesn't escape the value. Still, I
highlybrecommend using the query method and writing the full SQL query. In
the long term is a great thing to do
