### ISSUE TITLE
Fatal error: Using $this when not in object context

### ISSUE THREAD

**Issue by gucabansimon** [stefangabos/Zebra_Database#35]
Hi, im having this problem with the class. Its working perfectly on WAMP local server, but not in live (php5.3/nginx) ubuntu 14 vps.

that error was thrown using a dlookup() 

on (insert/select) on other script, the error was different, like 

- mysqli_real_escape_string(): invalid object r resource in mysql ...
- warning: array_pop() expect parameter 1 to be array null given ...

PS: Im not a pro coder...

**Comment by stefangabos** [comment]
This is most likely not related to Zebra_Database but to how you built your code but without seeing the code I cannot help

**Comment by gucabansimon** [comment]
Sir,

![untitled](https://user-images.githubusercontent.com/21140175/28850535-ddc0e348-7725-11e7-93c5-9b27c62fafce.jpg)
**local dev server**: windows 7 64bit, wamp 3.0.6 64bit

![untitled2](https://user-images.githubusercontent.com/21140175/28850616-565f0d02-7726-11e7-9c22-0a8d11f37259.jpg)
**live server**: https://free.budflick.com/phpinfo.php
**php source**: https://free.budflick.com/chat.phps

on my local machine, it works. all queries are executed, and console log is full of information.

on live server, it only works upto the setcharset command only, it did not execute the 2 query as shown in the php source.

it was the basic query i have, other query results to that error stated in the title of this thread :(

thanks!

**Comment by gucabansimon** [comment]
Sir, whats the possible remedy for this? Is it about my server configuration? I need your class as its easy to use and with caching mechanism. Thanks

**Comment by stefangabos** [comment]
I am sorry, I've looked at what you've sent me but without working with the actual code and on the actual hardware, I have no idea what can be wrong. Can you upgrade that PHP 5.3.10 on the live server? Maybe that's what is causing the issues?

**Comment by gucabansimon** [comment]
**SOLVED**: Seems the bug was on PHP 5.3.10. I reinstalled (Debian7 32bit, PHP5.4) and its working now. Cheers!
