### ISSUE TITLE
Error on Insert_Update Not properly escaping HTML

### ISSUE THREAD

**Issue by djeraseit** [stefangabos/Zebra_Database#41]
This is on insert_update. No functions for "values".

Zebra_Database (MySQL): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '<ul><li>Style: Brief</li><li>Material: Polyester/l' at line 5 in /var/www/html/tnt.amazingoverstock.com/public_html/vendor/stefangabos/zebra_database/Zebra_Database.php on line 2317
Zebra_Database (MySQL): the number of items to replace is different than the number of items in the <em>$replacements</em> array in /var/www/html/tnt.amazingoverstock.com/public_html/vendor/stefangabos/zebran line 2317

Zebra_Database (MySQL): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '<ul>
<li>Style: Casual</li>
<li>Material: Polyester</li>
<li>Silhouette: A-Line<' at line 5 in /var/www/html/tnt.amazingoverstock.com/public_html/vendor/stefangabos/zebra_database/Zebra_Database.php on line 2317

**Comment by stefangabos** [comment]
Can you please show me the actual query string you are running?

**Comment by djeraseit** [comment]
Forgive my ignorance. I'm going to close this as it is probably not your code. Thank you again for the wonderful library.
