### ISSUE TITLE
Insert_Bulk - Duplicate Key No Update?

### ISSUE THREAD

**Issue by djeraseit** [stefangabos/Zebra_Database#42]
Greetings,

Does the insert_bulk support on duplicate key update?

If not, should I use the query function?

Thank you!

**Comment by stefangabos** [comment]
Apparently it only supports IGNORE...
I'll look into it this weekend. Until then just use the query method

**Comment by stefangabos** [comment]
But there's [insert_update] which does that (https://stefangabos.github.io/Zebra_Database/Zebra_Database/Zebra_Database.html#methodinsert_update)

**Comment by stefangabos** [comment]
...but that works for a single record...
ok, i'll look into it this weekend and come up with something

**Comment by djeraseit** [comment]
any luck on improving the code? This is by far the best class ever! it doesn't escape ` very well though in insert_update. Even when forcing $db->escape($variable) on the $variable.

**Comment by stefangabos** [comment]
happy new year! :)
have a look at the new [insert_bulk](https://stefangabos.github.io/Zebra_Database/Zebra_Database/Zebra_Database.html#methodinsert_bulk) method

**Comment by djeraseit** [comment]
I just want to say thank you! I am using the new version but I haven't figured out how to use the database object in a function. I setup the connection in db.php and even if i pass $db as a parameter to the function i cannot use it. Any suggestions?

**Comment by stefangabos** [comment]
**very** old school way

```php
global $db;
$db = new Zebra_Database

function foo() {
    global $db;
    // $db is now available
}
```

old school
```php
$db = new Zebra_Database();

function foo() use ($db) {
    // $db is available
}
```

**Comment by stefangabos** [comment]
passing $db as a parameter should work as well. i forgot about this ancient technique! :)
