### ISSUE TITLE
Need update requirements for Zebra_Database class

### ISSUE THREAD

**Issue by jorovalkov** [stefangabos/Zebra_Database#44]
Hi @stefangabos, I saw you write the requirements are "PHP 5.2.0+ with the mysqli extension activated, MySQL 4.1.22+";
But, unfotunatelly, the latest version of wrapper cannot be used with php < 5.4, because is using $this in closures. 

> PHP Fatal error:  Using $this when not in object context in Zebra_Database.php on line 4492

**Comment by djeraseit** [comment]
You should really update your code to support the latest version of PHP
