### ISSUE TITLE
table_exists always return true

### ISSUE THREAD

**Issue by jorovalkov** [stefangabos/Zebra_Database#45]
Hi @stefangabos ,

The method table_exists always return true also when table do not exists. So when I changed the method (line 3626) like that is working:
// check if table exists in the database
        return $this->fetch_assoc($this->query('SHOW TABLES' . (isset($database) ? ' IN ' . $database : '') . ' LIKE ?', array($table))) **!=** false ? true : false;

**Comment by stefangabos** [comment]
Thank you!
