### ISSUE TITLE
Option to change the name of log file

### ISSUE THREAD

**Issue by jatubio** [stefangabos/Zebra_Database#47]
Hi!

I'm using the same folder for different web project. And when Zebra write the log file, I can't know from what web project comes. 

I would appreciate an option to set the name of log file or, at least, define one prefix.

**Comment by stefangabos** [comment]
Setting [log_path](https://stefangabos.github.io/Zebra_Database/Zebra_Database/Zebra_Database.html#var$log_path) to a full path to a file name and an extension will now correctly use that file name for logging - previously this was stated in the documentation but the logs were always written to log.txt
