### ISSUE TITLE
Error: mysqli_close() expects parameter 1 to be mysqli, boolean given

### ISSUE THREAD

**Issue by jatubio** [stefangabos/Zebra_Database#49]
If they are not connection openen and I call to `->close()` method, I get this error message:

Error: mysqli_close() expects parameter 1 to be mysqli, boolean given]

This is the line that throws error: `$result = @mysqli_close($this->connection);`

**Comment by stefangabos** [comment]
That's really weird as that's exactly why there's the `@` there, so that there's no error reported...

**Comment by jatubio** [comment]
I'm using php 7.2.1 with all errors enabled.

Thank you for fix them!

**Comment by aahco** [comment]
// Function to close the database
    function close() {
        // Closingdata base connection
        ((is_null($__mysqli_res=mysqli_close($GLOBALS["__mysqli_ston"]))) ? false : $__mysqli_res);
    }
