### ISSUE TITLE
Unknown column 'Max(Pagina)' in 'field list'

### ISSUE THREAD

**Issue by jatubio** [stefangabos/Zebra_Database#50]
Zebra is making this sql sentence:  

	SELECT
		`Max(Pagina)` AS Pagina
		FROM
		`contenidos_mod1` ORDER BY  Pagina ASC LIMIT 1

I think it's because of the method _is_mysql_function() that don't recognize `Max(Pagina)` as function. But I don't know how to fix this.

PS: Using the last commit on develop branch and working with the previous versions before changes on the `_is_mysql_function()` method

**Comment by jatubio** [comment]
I'm calling select method with these parameters:

$columns[0]=Max(Pagina) as Pagina
$order=Pagina ASC
$limit=1
$table=contenidos_mod1

This is the resulting sql: `SELECT Max(Pagina) as Pagina FROM `contenidos_mod1` ORDER BY Pagina ASC LIMIT 1` (with the older version of  `_is_mysql_function()`

**Comment by stefangabos** [comment]
Should work now

**Comment by jatubio** [comment]
Yes, it works like a charm.

Thank you!
