### ISSUE TITLE
Memcache Use Sample

### ISSUE THREAD

**Issue by sanater** [stefangabos/Zebra_Database#54]
Please add memcache use sample.

Too many queries going into the possibility of not using memcache.

`$db->query('select * from tblayar order by id DESC','',true);
while ($ayarlar = $db->fetch_obj()) {
	define($ayarlar->baslik,$ayarlar->icerik);
	
}`

Is the correct use?

**Comment by stefangabos** [comment]
See the example for [caching_method](https://stefangabos.github.io/Zebra_Database/Zebra_Database/Zebra_Database.html#var$caching_method).

Once `memcache` is properly set up, you would use the queries in the same way as you did before. see the documentation for the [query](https://stefangabos.github.io/Zebra_Database/Zebra_Database/Zebra_Database.html#methodquery) method and, more specifically, the 3rd argument, which has to be, i quote, *an integer representing the number of seconds after which the cache will be considered expired and the query executed again*

Therefore, your query would be something like
```php
$db->query('
    SELECT
        * 
    FROM 
        tblayar 
    ORDER BY
        id DESC
', '', 3600);
```
...for caching that result for an hour

**Comment by sanater** [comment]
thank you very much. it worked.
