### ISSUE TITLE
PHP 7.4.0 - Magic Quotes

### ISSUE THREAD

**Issue by userc479** [stefangabos/Zebra_Database#57]
I'm getting this issue as using PHP 7.4.0:

Deprecated: Function get_magic_quotes_gpc() is deprecated in C:\xampp\htdocs\assets\components\zebra_database\Zebra_Database.php on line 1315

Any chance of looking into this issue so it doesn't require reverting back to older version - many thanks :)

**Comment by stefangabos** [comment]
Fixed. See [commit](https://github.com/stefangabos/Zebra_Database/commit/8632ac9413f9f3e94ef41bfeec243861c79ba552)

Let me know if it works. Thank you!

**Comment by userc479** [comment]
Yes @stefangabos - that seems to have gotten rid of the error - thank you for sorting that out swiftly :)
