### ISSUE TITLE
window.onload being called infinitely

### ISSUE THREAD

**Issue by BHare1985** [stefangabos/Zebra_Database#58]
on chrome the window.onload is hitting the max callstack in /public/javascript/database.js

**Comment by stefangabos** [comment]
weird, i am using this on chrome everyday...are you sure there is nothing else?

**Comment by BHare1985** [comment]
Took another look; I've confirmed it's because I have 2 classes that I am constructing, each one with their own copy of the a Zebra_Database() instance on a single page, so database.js gets injected into the page twice and that's whats causing it.

Interestingly, if I just comment out `orgOnLoad = window.onload;` then it's fine and the formatter still works with no issues.

**Comment by stefangabos** [comment]
ok, i will make sure to prevent this from happening in these cases

**Comment by stefangabos** [comment]
should be fixed now
