### ISSUE TITLE
Enhancement: Don't show globals

### ISSUE THREAD

**Issue by BHare1985** [stefangabos/Zebra_Database#59]
I'd like to start off with great job on this. I really like how easy it is but still as powerful as you'd want. The formatter is extremely useful.

Showing the PHP globals, at least the $_SERVER ones are a pretty big security risk. I think its very useful feature but perhaps an opt-in.

Understandably, `$debug=false` is what should be set on production but sometimes I got to debug something on production because inconsistencies between dev and production (mostly database data). I have taken the precaution of using the `$debugger_ip` (great idea) but some people may use have dynamic ips so it can become a little inconvenient (but maybe it should be to debug prod).

With that said, many people start off with learning PHP and don't take the best practices of turning off debug when they should.

Just an idea, I could understand both sides of the fence on this.

**Comment by stefangabos** [comment]
ok, i will think of something

**Comment by stefangabos** [comment]
I've added a property. See [documentation](https://stefangabos.github.io/Zebra_Database/Zebra_Database/Zebra_Database.html#var$debug_show_globals)

**Comment by stefangabos** [comment]
i just read this now again, and i think what you want is the new "string" feature of `debug` - see [docs](https://stefangabos.github.io/Zebra_Database/Zebra_Database/Zebra_Database.html#var$debug) (if you are not already using it, that is)
