### ISSUE TITLE
Inserting null values

### ISSUE THREAD

**Issue by BHare1985** [stefangabos/Zebra_Database#60]
I am inserting some data like this

```
$this->repo->insert("account", [
	'id'       => $accountId,
	'email'    => $email,
	'password' => $this->hashPassword($password),
	'name'     => $name,
]);
```

and $name can sometimes be non-null and sometimes it's null all depending if the user filled it out. Intuitively, I expected the library to insert null if it's null. However, it keeps that column in but removes it as a value

```
INSERT INTO `account` (`id`, `email`, `password`, `name`) 
VALUES 
    (
        "I-W3V7E2U39WJM", "jbob@gm.com", 
        , "542057a08bf3f0daaa94bb14dd63bfdf81820d86a98b77525a4844bc074005a6"
    )
```

I thought maybe if I coalesce nulls to "NULL" it will do it, but it just inserts the word "NULL". Is my expectation that nulls are handled by default?

**Comment by stefangabos** [comment]
this looks like a bug and i will look into it
