### ISSUE TITLE
Regression when using insert() with null values

### ISSUE THREAD

**Issue by bmorg** [stefangabos/Zebra_Database#63]
The behavior of the `insert()` method regarding `null` values changed twice during the last three minor versions. I tested using the following code:

```php
$db->insert(
    'my_table',
    [
        'param1' => 'val1',
        'param2' => null,
    ]
);
```

In Zebra_Database `2.9.11` this creates the following MySQL query:

```MySQL
INSERT INTO `my_table` (`param1`, `param2`) 
VALUES 
    ('val1', NULL)
```

In `2.9.12`:

```MySQL
INSERT INTO `my_table` (`param1`, `param2`) 
VALUES 
    ("val1", "")
```

In `2.9.13`:

```MySQL
INSERT INTO `my_table` (`param1`, `param2`) 
VALUES 
    ("val1",)
```

The problem seems to be that the method `insert_bulk()` is not using the common `$replacements` mechanism of the `query()` method.

I'd recommend to restore the behavior of version `2.9.11` as to not introduce backwards incompatible changes during minor version upgrades.

**Comment by stefangabos** [comment]
This should be fixed in 2.9.14 which I just released and is available via Composer
Please let me know if it works

**Comment by bmorg** [comment]
Oh, great! I hadn't checked the `master` branch!

Thanks for the quick answer and thank you for your work!

**Comment by stefangabos** [comment]
thank **you** for taking the time to report!

**Comment by stefangabos** [comment]
i do you use the german language in the debugging console?

**Comment by bmorg** [comment]
When I'm using it I have it set to the default english. I personally find it easier not to switch between languages while programming.

**Comment by stefangabos** [comment]
ok. i was wondering if you can do some proofreading and translate the missing entries in the German language file. not a big deal and offense taken if you don't feel like doing it.

**Comment by bmorg** [comment]
Sure, I can have a look at it. I'll open a pull request.

**Comment by stefangabos** [comment]
thank you!
