### ISSUE TITLE
Wrong use of a variable in implode()

### ISSUE THREAD

**Issue by pbm845** [stefangabos/Zebra_Database#65]
https://github.com/stefangabos/Zebra_Database/blob/c616f5b8f9c85596eea7bee4732421d26622cb2f/Zebra_Database.php#L2102
It is apparent that the variable that is escaped must be $item

**Comment by stefangabos** [comment]
That is correct, it seems i broke it with [d4c17c6](https://github.com/stefangabos/Zebra_Database/commit/d4c17c60d4ad081bb114971bdb9315900a948fd2)

**Comment by stefangabos** [comment]
It is now fixed and I published a new release which should be available soon via Composer.
thanks a lot for reporting!
