### ISSUE TITLE
Deprecation warning when elvis operator used

### ISSUE THREAD

**Issue by Dibbyo456** [stefangabos/Zebra_Database#70]
````php
$db->update(
    'table_name',
    [
        'country' => $country ?: null,
        'state'   => $state ?: null,
    ],
  ...
);
````

```
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in zebra_database\Zebra_Database.php on line 4268

Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in zebra_database\Zebra_Database.php on line 4278
```

**Comment by stefangabos** [comment]
I don't get that in 7.3.19
what PHP are you running?
i do get where the errors comes from i just need to be able to reproduce it

**Comment by stefangabos** [comment]
it is not about the elvis operator but rather that internally the library tries to `trim()` the `null`

**Comment by Dibbyo456** [comment]
> what PHP are you running?

Sorry, forgot to mention it. I'm running PHP 8.1.2

**Comment by Dibbyo456** [comment]
> it is not about the elvis operator but rather that internally the library tries to `trim()` the `null`

oh yeah.. you're right..

**Comment by stefangabos** [comment]
It is fixed now - (it was introduced in PHP 8.1)
you'll have to download the latest as it is not yet available on composer

**Comment by stefangabos** [comment]
thanks for reporting and let me know if it works

**Comment by Dibbyo456** [comment]
Awesome. Thank you so much.
