### ISSUE TITLE
PHP 8 reports Mysql syntax errors with remote host

### ISSUE THREAD

**Issue by cosinus90** [stefangabos/Zebra_Database#76]
Hello, thanks for great package, I'm trying to use it with  8.1.13
Strange error reported

Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SHOW TABLES' at line 1 in /home/*/inc/Zebra_Database-master/Zebra_Database.php:3569 
Stack trace: #0 /home/*/inc/Zebra_Database-master/Zebra_Database.php(3569): mysqli_query() #1 /home/*/inc/Zebra_Database-master/examples/example.php(45): Zebra_Database->query() #2 {main} thrown in /home/*/inc/Zebra_Database-master/Zebra_Database.php on line 3569

There I corrected a bit your example.php that way

```
       $db->connect(

        );

        $db->set_charset();

        $db->query('SHOW TABLES');
        $rows = $db->fetch_assoc();
        print_r($rows);
```

I was suspecting the wrong system settings, but plain mysqli code works fine. Lst version downloaded from github.

**Comment by stefangabos** [comment]
Later this week I will publish a new release and you will be able to get it via composer. Until then you'll have to download it manually. 
Thank you for reporting the bug!
