### ISSUE TITLE
'IN' condition in delete command contains empty values

### ISSUE THREAD

**Issue by gmello77** [stefangabos/Zebra_Database#77]
Hi, I'm using the delete command this way:
`$db->delete(
        "orders_products",
        "orders_id IN (?)",
        array($orders_ids)
);`

where `$orders_ids` is an array with numeric values (something like `array(386, 1542, 18888)`). If I turn on debug the generated query is like 
`DELETE FROM orders_products WHERE orders_id IN ('','','','')`.

I'm doing something wrong?

**Comment by stefangabos** [comment]
I just tried this query and it worked fine

```php
$db->delete('city', 'ID IN (?)', array(array(1, 2, 3)));
```

Are you sure $orders_ids is an array?
Maybe do a ```var_dump($orders_id)``` just before the `delete`

**Comment by gmello77** [comment]
Sure, that's my var_dump:
`array(3) {
  [0]=>
  int(381)
  [1]=>
  int(14299)
  [2]=>
  int(14308)
}`.

The values inside the IN bracket are empty but the number of the values is correct (3 values in array, 3 values in IN condition). I'm on php 5.6, maybe could be the problem?

**Comment by stefangabos** [comment]
Ah, good ol' PHP 5.6! :)
Let me try it with that

**Comment by stefangabos** [comment]
Nope, must be something else. Just tried in PHP 5.6.40.
Are you using the latest of Zebra Database?

**Comment by stefangabos** [comment]
Ok, i think this is about [this](https://github.com/stefangabos/Zebra_Database/issues/65) bug, fixed in 2.10.1

**Comment by gmello77** [comment]
Correct! Updated with composer, now work like a charm. Thank you Stefan, Zebra Database is awesome!

**Comment by stefangabos** [comment]
I am glad it worked.
I'd appreciate a star for the repo if you haven't done it already.
Thanks!
