### ISSUE TITLE
set_charset() function in Zebra_Database breaks Lazy connection feature

### ISSUE THREAD

**Issue by Albatroon** [stefangabos/Zebra_Database#80]
Zebra_Database's set_charset() function violates the Lazy connection feature that connects to the database only when the first query is executed. The function initiates a connection to the database and sets the character set, resulting in an unnecessary connection being established to the database. Additionally, this behavior conflicts with the documentation, which recommends setting the charset immediately after connecting to the database.

The set_charset() function should follow the Lazy connection feature and defer the connection until the first query is executed. The function should save the requested charset and connect to the database only when necessary.

An example of the issue is shown below:

```
<?php
$db = new Zebra_Database();
$db->connect(DB_SERVER, DB_USER, DB_PASS, DB_DATABASE);
$db->set_charset("utf8mb4", "utf8mb4_unicode_ci");  // a connection is made here without any query requested
```

**Comment by stefangabos** [comment]
the `set_charset` method makes a call to the `query` method which does the check you are talking about. i'll have to queue this request until a _real_ query is done. i'll figure out something in the coming days

**Comment by stefangabos** [comment]
Thanks for suggesting this!
