### ISSUE TITLE
Respect "halt_on_errors" in non-debug mode

### ISSUE THREAD

**Issue by bmorg** [stefangabos/Zebra_Database#82]
When `debug` is set to `false` a lot of potential problems are silently swallowed by the `_log` function. (`error_log` is called, but no exception is thrown.)

In a lot of contexts (e.g. production environments) it might be preferable to raise an exception on database errors rather than returning a value like `[]` or `null`, as this can help in identifying underlying problems quickly and might save on debugging effort.

IMO `halt_on_errors` should be independent of the `debug` parameter, i.e. if `halt_on_errors` is `true` any error should trigger an exception.

@stefangabos What are your thoughts on this? Has this been discussed before? (I didn't find anything in the issues here on Github.) I can also provide a pull request for this.

**Comment by bmorg** [comment]
Unfortunately this problem propagates to everything using `query()`. So e.g. the method `get_tables` returns an empty `array` even if there were errors. And not all of these errors would be returned by `error()`, so there is no way to tell whether the empty array is the actually correct result or if there was an error.

Two examples to further elaborate on this:

```php
$db = new \Zebra_Database();
$db->debug = false;
$db->connect($host, $user, 'INVALID PASSWORD', $database);
var_dump($db->get_tables()); // empty array
var_dump($db->error()); // false
```

```php
$db = new \Zebra_Database();
$db->debug = false;
$db->connect($host, $user, $password, $database);
var_dump($db->get_tables('NONEXISTENT DATABASE')); // empty array
var_dump($db->error()); // 'Access denied ...'
```

**Comment by stefangabos** [comment]
i agree that `halt_on_errors` should probably be unrelated to the `debug` property
i'll have to look into this a little bit more but i welcome feedback and suggestions

**Comment by bmorg** [comment]
I personally have patched the library for now to raise a `RuntimeException ` in the `elseif` block in `_log` (after `error_log`):

```php
if ($fatal && $this->halt_on_errors) {
    throw new \RuntimeException('Zebra_Database (MySQL): ' . (isset($data['error']) ? $data['error'] : $data['message']));
}
```

(This might possibly imply that the method need to be renamed to something like `_handle_error`.)

But I'm guessing this will break backward compatibility for a lot of users that rely on errors being silently ignored.

**Comment by stefangabos** [comment]
I found a way to not break backward compatibility by allowing the value of `always` for this property case in which it will raise an exception as per your code. I updated the [documentation](https://stefangabos.github.io/Zebra_Database/Zebra_Database/Zebra_Database.html#var$halt_on_errors) but, as I also say in the docs, I recommend using the `debug` property with a string value in case you need to debug in production without affecting overall functionality
