### ISSUE TITLE
Better error handling in dcount

### ISSUE THREAD

**Issue by bmorg** [stefangabos/Zebra_Database#83]
The `dcount` method silently returns `null` or `false` when a `$replacements` array with the wrong number of parameters is provided.

Consider the following program:

```php
$db = new \Zebra_Database();
$db->debug = false;
$db->connect($host, $user, $password, $database);

$count1 = $db->dcount('*', 'users', 'username=?', ['user1']);
$count2 = $db->dcount('*', 'users', 'username=?', ['user1', 'group1']); // wrong number of replacements
```

The last line should produce an error (see also #82). Instead `null` is returned.  The responsible code in `dcount` is this:

```php
// if query was executed successfully and one or more records were returned
if (isset($this->last_result) && $this->last_result !== false && $this->returned_rows > 0) {

    // fetch the result
    $row = $this->fetch_assoc();

    // return the result
    return $row['counted'];

}
```

**BUT** in the second call to `dcount` the values of `$this->last_result` and `$this->returned_rows` are still set **from the first call** to `dcount`, not the second one, so the `if` condition does not check the correct thing.

`$this->fetch_assoc()` returns `null` because the result has already been retrieved in the first call.

When the first call is removed the result changes to `false`.

**Comment by stefangabos** [comment]
yes, that is correct. it looks like i am unsetting those values too late in that case: if there's an issue with the parameters, i return from the `query` method before unsetting those two properties
