### ISSUE TITLE
Throw error when multiple tables used in select()

### ISSUE THREAD

**Issue by bmorg** [stefangabos/Zebra_Database#84]
According to the [documentation](https://stefangabos.github.io/Zebra_Database/Zebra_Database/Zebra_Database.html#methodselect) `select()` should only be used "for simple `SELECT` queries", but the method currently allows specifying multiple tables as well:

```php
$db->select(
    '*',
    'table1, table2',
    'table1.ref=table2.id'
);
```

**But** this starts failing when using table aliases:

```php
$db->select(
    '*',
    'table1 AS t1, table2 AS t2',
    't1.ref=t2.id'
);
```

This results in the following broken query, cutting off the second alias:

```MySQL
SELECT
    *
FROM
    `table1` AS t1, table2 WHERE t1.ref=t2.id
```

IMO `select()` should always throw an exception when used with multiple tables.

**Comment by stefangabos** [comment]
yes, because it does 
`$this->_escape($table)`
on the value
but i don't know of a safe way of knowing if there were multiple tables specified. nor if it is critical to implement this.
one may or may not use `AS` keyword, there can be commas like in your example, or various types of `JOIN`s

**Comment by bmorg** [comment]
> there can be commas like in your example, or various types of `JOIN`s

Good point. Although `JOINS` also already lead to invalid SQL, e.g.:

```php
$db->select(
    '*',
    'table1 INNER JOIN table2 ON table1.ref=table2.id'
);
```

Resulting SQL:

```MySQL
SELECT
    *
FROM
    `table1 INNER JOIN table2 ON table1`.`ref=table2`.`id`        
```

**Comment by stefangabos** [comment]
I know :) that's why I am saying that is not an easy fix nor do I think this should be patched anyway. it is not meant for that

**Comment by bmorg** [comment]
You might be correct, I'm also not a 100% sure how to detect this. But I had a quick look at the [MySQL specification](https://dev.mysql.com/doc/refman/8.0/en/join.html) and it looks like a comma and a literal `JOIN` might (?) be the only ways to select multiple tables.

So meanwhile, locally, I just brutally patched the method (to protect me against myself) like this:

```php
// API safeguard: Zebra_Database only sometimes supports select() for multiple tables
// https://github.com/stefangabos/Zebra_Database/issues/84
if (   strpos($table, ',') !== false
    || preg_match('/\sJOIN\s/i', $table)
) {
    throw new ZebraDatabaseException('select() can\'t be used with multiple tables');
}
```

This will break code that specifies the table name as `' join '` (with the spaces), but I can live with that in my installations.

Feel free to close this issue if this is a `wontfix` in your opinion.

**Comment by stefangabos** [comment]
this is reasonable but we also need to cater for aliases as those will break too. 
there will be incorrect results when table names are given as `tablename AS alias` or as `tablename alias` because of how the escaping is applied

**Comment by stefangabos** [comment]
I will not fix this as I think it is an edge case and there is no generally viable solution
